const data = {
  products: [
    {
      _id: '1',
      name: 'Wood King Bed',
      category: 'Beds',
      image: '/images/f1.jpg',
      price: 12816,
      brand: ' IKEA',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Metal Double Bed',
      category: 'Beds',
      image: '/images/f2.jpg',
      price: 6290,
      brand: ' IKEA',
      rating: 4.2,
      numReviews: 5,
      countInStock: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'King Box Bed',
      category: 'Beds',
      image: '/images/f3.jpg',
      price: 28380,
      brand: ' IKEA',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    }, {
      _id: '4',
      name: 'Drawer Storage For Bedroom',
      category: 'Beds',
      image: '/images/f4.jpg',
      price: 20249,
      brand: ' IKEA',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      description: 'high quality product',
    },
  ],
};
export default data;
